/* AUTOGENERATED FILE — projectId only. Keys must come from env vars. */

export const projectId = "esmuegorbzltpkpmnxzu"
// publicAnonKey removed — use VITE_SUPABASE_ANON_KEY env var instead.
// Never hardcode API keys in source files.